name: CI/CD Pipeline Local Docker
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupération du code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Installation de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Installer les dépendances npm
      - name: Install dependencies
        run: npm install

      # 4️⃣ Exécuter les tests
      - name: Run tests
        run: npm test

      # 5️⃣ Construire l'image Docker localement
      - name: Build Docker image locally
        run: docker build -t node-app:staging .